#!/bin/bash
#Script by weihongloke
figlet -cf slant "Welcome" | lolcat
figlet -cf slant "Free AutoScript " | lolcat
echo -e "    #====================================================================#" | lolcat
echo -e "    #                  Premium Script By PrinceNewbie                    #" | lolcat
echo -e "    #                                                                    #" | lolcat
echo -e " ████████╗███████╗███╗   ███╗██████╗  █████╗  ██████╗ ███████╗   " | lolcat
echo -e "╚══██╔══╝██╔════╝████╗ ████║██╔══██╗██╔══██╗██╔════╝ ██╔════╝    " | lolcat
echo -e "   ██║   █████╗  ██╔████╔██║██████╔╝███████║██║  ███╗█████╗      " | lolcat
echo -e "   ██║   ██╔══╝  ██║╚██╔╝██║██╔══██╗██╔══██║██║   ██║██╔══╝      " | lolcat
echo -e "   ██║   ███████╗██║ ╚═╝ ██║██║  ██║██║  ██║╚██████╔╝███████╗    " | lolcat
echo -e "   ╚═╝   ╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝    " | lolcat
echo -e "    #                                                                    #" | lolcat     
echo -e "    #          │▒│▒|▒│▒│     - For those who use this script,            #" | lolcat
echo -e "    #         ┌┴─┴─┐-┘─┘       this script is still under development    #" | lolcat
echo -e "    #         │▒┌──┘▒▒▒│     - Thanks for using this script          #" | lolcat
echo -e "    #         └┐▒▒▒▒▒▒┌┘     - To EnterMenuList = 'menu'                 #" | lolcat
echo -e "    #                                                                    #" | lolcat
echo -e "    #====================================================================#" | lolcat
